name: Mass Update Manifest
on:
  workflow_dispatch:
    inputs:
      PackageIdentifier:
        description: "Package Identifier"
        required: true

jobs:
  update:
    name: Update manifests
    runs-on: windows-latest
    env:
      WINGET_PKGS_FORK_REPO: ${{vars.WINGET_PKGS_FORK_REPO}}
      WINGET_PAT: ${{secrets.WINGET_PAT}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: pipeline
      - name: Checkout winget-pkgs fork
        uses: actions/checkout@v4
        with:
          repository: ${{env.WINGET_PKGS_FORK_REPO}}
          token: ${{env.WINGET_PAT}}
          fetch-depth: 2
          path: fork
      - name: Trigger Mass Package Update
        run: |
          Write-Host "Currently in: $(Get-Location)"
          $fullPathFork = "$(Get-Location)\fork"
          Set-Location pipeline
          Scripts/Update-ExistingManifest.ps1 -PackageIdentifier ${{ github.event.inputs.PackageIdentifier }} -OutputDir $fullPath
