name: Update Package Count Badge
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - .github/workflows/update-github-packages-*.yml
            - .github/workflows/update-via-script.yml
jobs:
    update-package-count:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: pip install pyyaml
            - name: Count packages
              id: count
              run: |
                echo "countgithub=$(python3 scripts/package_count_raw.py github-releases-monitored.yml)" >> $GITHUB_OUTPUT
                echo "countscript=$(python3 scripts/package_count_matrix.py .github/workflows/update-script-packages.yml)" >> $GITHUB_OUTPUT
            - name: Update README
              run: |
                countgithub=${{ steps.count.outputs.countgithub }}
                countscript=${{ steps.count.outputs.countscript }}
                sed -i "s/ScriptPackages-[0-9]*-green/ScriptPackages-$countscript-green/g" README.md
                sed -i "s/GithubPackages-[0-9]*-blue/GithubPackages-$countgithub-blue/g" README.md
            - name: Commit and push
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                commit_message: Update package count badge
                file_pattern: README.md
