name: Rebuild Package Manifests
on:
  workflow_dispatch:
    inputs:
      PackageIdentifier:
        description: "Package Identifier"
        required: true
      submit:
        description: 'True to auto-submit'
        required: true
        type: boolean
        default: false
      resolves: 
        description: 'resolves this issues'
        required: false
        default: ''
jobs:
  update:
    name: Rebuild manifests
    runs-on: windows-latest
    env:
      WINGET_PKGS_FORK_REPO: ${{vars.WINGET_PKGS_FORK_REPO}}
      GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trigger Mass Package Update
        run: |
          $fullPathFork = "$(Get-Location)"
          $resolves = ${{ github.event.inputs.resolves }}
          scripts/Update-AllPackageManifests.ps1 -PackageIdentifier ${{ github.event.inputs.PackageIdentifier }} -OutputDir $fullPathFork -Token ${{env.GITHUB_TOKEN}} -Submit ${{ github.event.inputs.submit }} ( ![string]::IsNullOrWhitespace($resolves) ? "-Resolves  $resolves" : $null ) 
      - uses: actions/upload-artifact@v4
        with:
          name: manifests
          path: manifests
