name: Selfhost - Test Manifest

on:
  workflow_dispatch:
    inputs:
      ManifestURL:
        description: "Manifest URL"
        required: false
      PRNumber:
        description: "PR Number"
        required: false
      Timeout:
        description: "Timeout in seconds (default: 300)"
        required: false
        type: number
        default: 300

jobs:
  test:
    name: "Test manifest - PR #${{ inputs.PRNumber }}"
    runs-on: [self-hosted, windows, x64]
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Manifest Package Name
        id: manifest
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $manifestUrl = "${{ inputs.ManifestURL }}"
          if( $manifestUrl -eq "" -and "${{ inputs.PRNumber }}" -eq "" ) {
            echo "ManifestURL and PR-Number is empty. Exiting."
            exit 1
          }
          if( $manifestUrl -eq "" ) {
            Import-Module .\modules\WingetMaintainerModule
            $manifestUrl = Get-ManifestUrlByWingetPkgsPrNumber -PrNumber "${{ inputs.PRNumber }}"
          }

          # The regex explanation:
          # .*\/manifests\/        matches everything up to '/manifests/'
          # [^/]+\/                matches the dynamic folder immediately after manifests
          # ([^/]+)\/              captures the username into group 1
          # ([^/]+)\/              captures the package name into group 2
          # ([^/]+)\/?             captures the version into group 3 (with an optional trailing slash)
          $pattern = ".*/manifests/[^/]+/([^/]+)/([^/]+)/([^/]+)/?$"
          $result = [regex]::Replace($manifestUrl, $pattern, '$1.$2_$3')

          echo "manifestname=$result" >> $env:GITHUB_ENV
          echo "manifesturl=$manifestUrl" >> $env:GITHUB_ENV

      - name: Test installation
        id: test
        shell: powershell
        env:
          TIMEOUT: ${{ inputs.Timeout }}
        run: .\scripts\testing\Test-Manifest-Host.ps1 -ManifestURL ${{ env.manifesturl }}
        #continue-on-error: true
